-- phpMyAdmin SQL Dump
-- version 4.3.11
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Dec 05, 2016 at 11:41 AM
-- Server version: 5.6.24
-- PHP Version: 5.6.8

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `project`
--

-- --------------------------------------------------------

--
-- Table structure for table `admin`
--

CREATE TABLE IF NOT EXISTS `admin` (
  `id` int(11) NOT NULL,
  `username` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `admin`
--

INSERT INTO `admin` (`id`, `username`, `password`) VALUES
(1, 'admin', '827ccb0eea8a706c4c34a16891f84e7b'),
(2, 'admin2', '827ccb0eea8a706c4c34a16891f84e7b');

-- --------------------------------------------------------

--
-- Table structure for table `advertisment`
--

CREATE TABLE IF NOT EXISTS `advertisment` (
  `id` int(11) NOT NULL,
  `link` varchar(255) NOT NULL,
  `picture` varchar(255) NOT NULL,
  `type` varchar(30) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `advertisment`
--

INSERT INTO `advertisment` (`id`, `link`, `picture`, `type`) VALUES
(7, 'www.google.com.my', 'advertisment/171200_091119_1.jpg', 'mainpage'),
(8, 'www.google.com.my', 'advertisment/171216_091142_2.jpg', 'ad1'),
(9, 'www.google.com.my', 'advertisment/171228_091155_3.jpg', 'ad2');

-- --------------------------------------------------------

--
-- Table structure for table `designer`
--

CREATE TABLE IF NOT EXISTS `designer` (
  `id` int(11) NOT NULL,
  `username` varchar(12) NOT NULL,
  `userpassword` varchar(255) NOT NULL,
  `useremail` varchar(30) NOT NULL,
  `userfullname` varchar(100) NOT NULL,
  `usercompanyname` varchar(100) NOT NULL,
  `userphonenumber` varchar(100) NOT NULL,
  `userpicture` varchar(100) NOT NULL,
  `userdescription` varchar(255) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `designer`
--

INSERT INTO `designer` (`id`, `username`, `userpassword`, `useremail`, `userfullname`, `usercompanyname`, `userphonenumber`, `userpicture`, `userdescription`) VALUES
(7, 'nayoung', '827ccb0eea8a706c4c34a16891f84e7b', 'nayoung@hotmail.com', 'Im Na Young', 'NY Interior Design', '0161234567', 'picture/181254_131100_DT4dVtB.jpg', 'Hi, This is NY interior design. Based on Korea'),
(8, 'So Hye', '827ccb0eea8a706c4c34a16891f84e7b', 'sohye@hotmail.com', 'Kim So Hye', 'SH Interior Design', '0101234567', 'picture/181215_151256_20140620-DSC_7224.jpg', 'Hi, This is SH interior design. Based on Korea'),
(9, 'Se Jeong', '827ccb0eea8a706c4c34a16891f84e7b', 'sejeong@hotmail.com', 'Kim Se Jeong', 'SJ Interior Design', '0121234567', 'picture/181211_121131_160521_03.jpg', 'Hi, This is SJ interior design. Based on Korea');

-- --------------------------------------------------------

--
-- Table structure for table `portfolio`
--

CREATE TABLE IF NOT EXISTS `portfolio` (
  `id` int(11) NOT NULL,
  `description` varchar(255) NOT NULL,
  `picture` varchar(255) NOT NULL,
  `tags` varchar(255) NOT NULL,
  `userid` varchar(255) NOT NULL,
  `title` varchar(255) NOT NULL,
  `price` varchar(40) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=196 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `portfolio`
--

INSERT INTO `portfolio` (`id`, `description`, `picture`, `tags`, `userid`, `title`, `price`) VALUES
(40, 'The foundational Zen concepts of self-control and meditation translate to certain styles of interior design quite well. This two-bedroom home, for example, uses simple furniture and clean forms to help clear the mind of distractions and preoccupations to ', 'portfolio/Se Jeong_20161205_180651_asian-bedroom-decor-inspiration-600x380.jpg', 'asian,china,chinese,modern', 'sejeong@hotmail.com', 'A Beautiful 2 Bedroom Modern Chinese House With Zen Elements (Includes 3D Floor Plan)', 'RM20000'),
(41, 'The foundational Zen concepts of self-control and meditation translate to certain styles of interior design quite well. This two-bedroom home, for example, uses simple furniture and clean forms to help clear the mind of distractions and preoccupations to ', 'portfolio/Se Jeong_20161205_180652_black-and-white-interior-design-300x250.jpg', 'asian,china,chinese,modern', 'sejeong@hotmail.com', 'A Beautiful 2 Bedroom Modern Chinese House With Zen Elements (Includes 3D Floor Plan)', 'RM20000'),
(42, 'The foundational Zen concepts of self-control and meditation translate to certain styles of interior design quite well. This two-bedroom home, for example, uses simple furniture and clean forms to help clear the mind of distractions and preoccupations to ', 'portfolio/Se Jeong_20161205_180652_bright-interior-accent-color-examples-300x250.jpg', 'asian,china,chinese,modern', 'sejeong@hotmail.com', 'A Beautiful 2 Bedroom Modern Chinese House With Zen Elements (Includes 3D Floor Plan)', 'RM20000'),
(43, 'The foundational Zen concepts of self-control and meditation translate to certain styles of interior design quite well. This two-bedroom home, for example, uses simple furniture and clean forms to help clear the mind of distractions and preoccupations to ', 'portfolio/Se Jeong_20161205_180652_chinese-bedroom-wardrobe-inspiration-600x380.jpg', 'asian,china,chinese,modern', 'sejeong@hotmail.com', 'A Beautiful 2 Bedroom Modern Chinese House With Zen Elements (Includes 3D Floor Plan)', 'RM20000'),
(44, 'The foundational Zen concepts of self-control and meditation translate to certain styles of interior design quite well. This two-bedroom home, for example, uses simple furniture and clean forms to help clear the mind of distractions and preoccupations to ', 'portfolio/Se Jeong_20161205_180652_chinese-home-decor-ideas-600x380.jpg', 'asian,china,chinese,modern', 'sejeong@hotmail.com', 'A Beautiful 2 Bedroom Modern Chinese House With Zen Elements (Includes 3D Floor Plan)', 'RM20000'),
(45, 'The foundational Zen concepts of self-control and meditation translate to certain styles of interior design quite well. This two-bedroom home, for example, uses simple furniture and clean forms to help clear the mind of distractions and preoccupations to ', 'portfolio/Se Jeong_20161205_180652_chinese-home-decor-inspiration-600x380.jpg', 'asian,china,chinese,modern', 'sejeong@hotmail.com', 'A Beautiful 2 Bedroom Modern Chinese House With Zen Elements (Includes 3D Floor Plan)', 'RM20000'),
(46, 'The foundational Zen concepts of self-control and meditation translate to certain styles of interior design quite well. This two-bedroom home, for example, uses simple furniture and clean forms to help clear the mind of distractions and preoccupations to ', 'portfolio/Se Jeong_20161205_180652_chinese-home-office-with-zen-decor-600x380.jpg', 'asian,china,chinese,modern', 'sejeong@hotmail.com', 'A Beautiful 2 Bedroom Modern Chinese House With Zen Elements (Includes 3D Floor Plan)', 'RM20000'),
(47, 'The foundational Zen concepts of self-control and meditation translate to certain styles of interior design quite well. This two-bedroom home, for example, uses simple furniture and clean forms to help clear the mind of distractions and preoccupations to ', 'portfolio/Se Jeong_20161205_180652_chinese-interior-wall-divider-600x380.jpg', 'asian,china,chinese,modern', 'sejeong@hotmail.com', 'A Beautiful 2 Bedroom Modern Chinese House With Zen Elements (Includes 3D Floor Plan)', 'RM20000'),
(48, 'The foundational Zen concepts of self-control and meditation translate to certain styles of interior design quite well. This two-bedroom home, for example, uses simple furniture and clean forms to help clear the mind of distractions and preoccupations to ', 'portfolio/Se Jeong_20161205_180652_chinese-latticework-600x380.jpg', 'asian,china,chinese,modern', 'sejeong@hotmail.com', 'A Beautiful 2 Bedroom Modern Chinese House With Zen Elements (Includes 3D Floor Plan)', 'RM20000'),
(49, 'The foundational Zen concepts of self-control and meditation translate to certain styles of interior design quite well. This two-bedroom home, for example, uses simple furniture and clean forms to help clear the mind of distractions and preoccupations to ', 'portfolio/Se Jeong_20161205_180652_chinese-two-bedroom-home-layout-600x454.jpg', 'asian,china,chinese,modern', 'sejeong@hotmail.com', 'A Beautiful 2 Bedroom Modern Chinese House With Zen Elements (Includes 3D Floor Plan)', 'RM20000'),
(50, 'The foundational Zen concepts of self-control and meditation translate to certain styles of interior design quite well. This two-bedroom home, for example, uses simple furniture and clean forms to help clear the mind of distractions and preoccupations to ', 'portfolio/Se Jeong_20161205_180652_chinese-zen-bedroom-decor-600x380.jpg', 'asian,china,chinese,modern', 'sejeong@hotmail.com', 'A Beautiful 2 Bedroom Modern Chinese House With Zen Elements (Includes 3D Floor Plan)', 'RM20000'),
(51, 'The foundational Zen concepts of self-control and meditation translate to certain styles of interior design quite well. This two-bedroom home, for example, uses simple furniture and clean forms to help clear the mind of distractions and preoccupations to ', 'portfolio/Se Jeong_20161205_180652_chinese-zen-home-decor-600x380.jpg', 'asian,china,chinese,modern', 'sejeong@hotmail.com', 'A Beautiful 2 Bedroom Modern Chinese House With Zen Elements (Includes 3D Floor Plan)', 'RM20000'),
(52, 'The foundational Zen concepts of self-control and meditation translate to certain styles of interior design quite well. This two-bedroom home, for example, uses simple furniture and clean forms to help clear the mind of distractions and preoccupations to ', 'portfolio/Se Jeong_20161205_180652_chinese-zen-table-place-setting-600x380.jpg', 'asian,china,chinese,modern', 'sejeong@hotmail.com', 'A Beautiful 2 Bedroom Modern Chinese House With Zen Elements (Includes 3D Floor Plan)', 'RM20000'),
(53, 'The foundational Zen concepts of self-control and meditation translate to certain styles of interior design quite well. This two-bedroom home, for example, uses simple furniture and clean forms to help clear the mind of distractions and preoccupations to ', 'portfolio/Se Jeong_20161205_180652_contemporary-chinese-home-design-600x380.jpg', 'asian,china,chinese,modern', 'sejeong@hotmail.com', 'A Beautiful 2 Bedroom Modern Chinese House With Zen Elements (Includes 3D Floor Plan)', 'RM20000'),
(54, 'The foundational Zen concepts of self-control and meditation translate to certain styles of interior design quite well. This two-bedroom home, for example, uses simple furniture and clean forms to help clear the mind of distractions and preoccupations to ', 'portfolio/Se Jeong_20161205_180652_cute-modern-chinese-kitchen-600x380.jpg', 'asian,china,chinese,modern', 'sejeong@hotmail.com', 'A Beautiful 2 Bedroom Modern Chinese House With Zen Elements (Includes 3D Floor Plan)', 'RM20000'),
(72, 'Two trends of the moment, black and white and Scandinavian themes can make quite a pair. Weâ€™ve found two apartments that use the trends wisely, putting Scandinaviaâ€™s busy simplicity and black and whiteâ€™s dramatic effects to good design use. The firs', 'portfolio/Se Jeong_20161205_181344_Abandoned-manor-living-room-open-French-doors-high-ceilings-iron-ore-staircase-575x325.jpg', 'black and white, scandinavian', 'sejeong@hotmail.com', 'Black And White Scandinavian Interiors That Explore The Dark Side', 'RM20000'),
(73, 'Two trends of the moment, black and white and Scandinavian themes can make quite a pair. Weâ€™ve found two apartments that use the trends wisely, putting Scandinaviaâ€™s busy simplicity and black and whiteâ€™s dramatic effects to good design use. The firs', 'portfolio/Se Jeong_20161205_181344_arched-white-window-black-cabinetry-monochrome-kitchen.jpg', 'black and white, scandinavian', 'sejeong@hotmail.com', 'Black And White Scandinavian Interiors That Explore The Dark Side', 'RM20000'),
(74, 'Two trends of the moment, black and white and Scandinavian themes can make quite a pair. Weâ€™ve found two apartments that use the trends wisely, putting Scandinaviaâ€™s busy simplicity and black and whiteâ€™s dramatic effects to good design use. The firs', 'portfolio/Se Jeong_20161205_181344_banquet-light-potted-plants-black-and-white-living-area.jpg', 'black and white, scandinavian', 'sejeong@hotmail.com', 'Black And White Scandinavian Interiors That Explore The Dark Side', 'RM20000'),
(75, 'Two trends of the moment, black and white and Scandinavian themes can make quite a pair. Weâ€™ve found two apartments that use the trends wisely, putting Scandinaviaâ€™s busy simplicity and black and whiteâ€™s dramatic effects to good design use. The firs', 'portfolio/Se Jeong_20161205_181344_bird-cage-lighting-Scandinavian-kitchen-table.jpg', 'black and white, scandinavian', 'sejeong@hotmail.com', 'Black And White Scandinavian Interiors That Explore The Dark Side', 'RM20000'),
(76, 'Two trends of the moment, black and white and Scandinavian themes can make quite a pair. Weâ€™ve found two apartments that use the trends wisely, putting Scandinaviaâ€™s busy simplicity and black and whiteâ€™s dramatic effects to good design use. The firs', 'portfolio/Se Jeong_20161205_181344_black-and-white-photographs-film-noir-sitting-space.jpg', 'black and white, scandinavian', 'sejeong@hotmail.com', 'Black And White Scandinavian Interiors That Explore The Dark Side', 'RM20000'),
(77, 'Two trends of the moment, black and white and Scandinavian themes can make quite a pair. Weâ€™ve found two apartments that use the trends wisely, putting Scandinaviaâ€™s busy simplicity and black and whiteâ€™s dramatic effects to good design use. The firs', 'portfolio/Se Jeong_20161205_181344_black-and-white-tiling-film-noir-bathroom.jpg', 'black and white, scandinavian', 'sejeong@hotmail.com', 'Black And White Scandinavian Interiors That Explore The Dark Side', 'RM20000'),
(78, 'Two trends of the moment, black and white and Scandinavian themes can make quite a pair. Weâ€™ve found two apartments that use the trends wisely, putting Scandinaviaâ€™s busy simplicity and black and whiteâ€™s dramatic effects to good design use. The firs', 'portfolio/Se Jeong_20161205_181344_black-frame-tile-shower-minimal-bathroom.jpg', 'black and white, scandinavian', 'sejeong@hotmail.com', 'Black And White Scandinavian Interiors That Explore The Dark Side', 'RM20000'),
(79, 'Two trends of the moment, black and white and Scandinavian themes can make quite a pair. Weâ€™ve found two apartments that use the trends wisely, putting Scandinaviaâ€™s busy simplicity and black and whiteâ€™s dramatic effects to good design use. The firs', 'portfolio/Se Jeong_20161205_181344_black-iron-stencil-and-glass-table-film-noir-living-space.jpg', 'black and white, scandinavian', 'sejeong@hotmail.com', 'Black And White Scandinavian Interiors That Explore The Dark Side', 'RM20000'),
(80, 'Two trends of the moment, black and white and Scandinavian themes can make quite a pair. Weâ€™ve found two apartments that use the trends wisely, putting Scandinaviaâ€™s busy simplicity and black and whiteâ€™s dramatic effects to good design use. The firs', 'portfolio/Se Jeong_20161205_181344_black-SMEG-fridge-Scandinavian-kitchen.jpg', 'black and white, scandinavian', 'sejeong@hotmail.com', 'Black And White Scandinavian Interiors That Explore The Dark Side', 'RM20000'),
(81, 'Two trends of the moment, black and white and Scandinavian themes can make quite a pair. Weâ€™ve found two apartments that use the trends wisely, putting Scandinaviaâ€™s busy simplicity and black and whiteâ€™s dramatic effects to good design use. The firs', 'portfolio/Se Jeong_20161205_181344_black-wall-standing-flower-lampshade-film-noir-bedroom.jpg', 'black and white, scandinavian', 'sejeong@hotmail.com', 'Black And White Scandinavian Interiors That Explore The Dark Side', 'RM20000'),
(82, 'Two trends of the moment, black and white and Scandinavian themes can make quite a pair. Weâ€™ve found two apartments that use the trends wisely, putting Scandinaviaâ€™s busy simplicity and black and whiteâ€™s dramatic effects to good design use. The firs', 'portfolio/Se Jeong_20161205_181344_black-walls-white-fixtures-monochrome-living-space.jpg', 'black and white, scandinavian', 'sejeong@hotmail.com', 'Black And White Scandinavian Interiors That Explore The Dark Side', 'RM20000'),
(83, 'Two trends of the moment, black and white and Scandinavian themes can make quite a pair. Weâ€™ve found two apartments that use the trends wisely, putting Scandinaviaâ€™s busy simplicity and black and whiteâ€™s dramatic effects to good design use. The firs', 'portfolio/Se Jeong_20161205_181344_black-wall-white-French-door-film-noir-entrance.jpg', 'black and white, scandinavian', 'sejeong@hotmail.com', 'Black And White Scandinavian Interiors That Explore The Dark Side', 'RM20000'),
(84, 'Two trends of the moment, black and white and Scandinavian themes can make quite a pair. Weâ€™ve found two apartments that use the trends wisely, putting Scandinaviaâ€™s busy simplicity and black and whiteâ€™s dramatic effects to good design use. The firs', 'portfolio/Se Jeong_20161205_181344_cat-painting-black-storage-cabinet-monochrome-workshop.jpg', 'black and white, scandinavian', 'sejeong@hotmail.com', 'Black And White Scandinavian Interiors That Explore The Dark Side', 'RM20000'),
(85, 'Two trends of the moment, black and white and Scandinavian themes can make quite a pair. Weâ€™ve found two apartments that use the trends wisely, putting Scandinaviaâ€™s busy simplicity and black and whiteâ€™s dramatic effects to good design use. The firs', 'portfolio/Se Jeong_20161205_181344_chocolate-brown-entranceway-Scandinavian-feel.jpg', 'black and white, scandinavian', 'sejeong@hotmail.com', 'Black And White Scandinavian Interiors That Explore The Dark Side', 'RM20000'),
(86, 'Two trends of the moment, black and white and Scandinavian themes can make quite a pair. Weâ€™ve found two apartments that use the trends wisely, putting Scandinaviaâ€™s busy simplicity and black and whiteâ€™s dramatic effects to good design use. The firs', 'portfolio/Se Jeong_20161205_181344_Chrome-features-kitchen-all-black-panelling-concrete-floor-575x325.jpg', 'black and white, scandinavian', 'sejeong@hotmail.com', 'Black And White Scandinavian Interiors That Explore The Dark Side', 'RM20000'),
(87, 'Two trends of the moment, black and white and Scandinavian themes can make quite a pair. Weâ€™ve found two apartments that use the trends wisely, putting Scandinaviaâ€™s busy simplicity and black and whiteâ€™s dramatic effects to good design use. The firs', 'portfolio/Se Jeong_20161205_181344_chrome-stove-and-oven-Scandinavian-kitchen.jpg', 'black and white, scandinavian', 'sejeong@hotmail.com', 'Black And White Scandinavian Interiors That Explore The Dark Side', 'RM20000'),
(88, 'Designer and visualization artist Andrei Lychkouski designed this Minsk apartment for a bachelor with an eclectic taste for styles that span eras and archetypes â€“ the result is a mixture between the traditional and the ultramodern, carefully decorated w', 'portfolio/Se Jeong_20161205_181916_awesome-bookshelf-inspiration.jpg', 'bachelor pad', 'sejeong@hotmail.com', 'A Beautiful One Bedroom Bachelor Apartment Under 100 Square Meters (With Floor Plan)', 'RM20000'),
(89, 'Designer and visualization artist Andrei Lychkouski designed this Minsk apartment for a bachelor with an eclectic taste for styles that span eras and archetypes â€“ the result is a mixture between the traditional and the ultramodern, carefully decorated w', 'portfolio/Se Jeong_20161205_181916_bachelor-apartment-bathroom-design.jpg', 'bachelor pad', 'sejeong@hotmail.com', 'A Beautiful One Bedroom Bachelor Apartment Under 100 Square Meters (With Floor Plan)', 'RM20000'),
(90, 'Designer and visualization artist Andrei Lychkouski designed this Minsk apartment for a bachelor with an eclectic taste for styles that span eras and archetypes â€“ the result is a mixture between the traditional and the ultramodern, carefully decorated w', 'portfolio/Se Jeong_20161205_181916_bachelor-apartment-kitchen-design.jpg', 'bachelor pad', 'sejeong@hotmail.com', 'A Beautiful One Bedroom Bachelor Apartment Under 100 Square Meters (With Floor Plan)', 'RM20000'),
(91, 'Designer and visualization artist Andrei Lychkouski designed this Minsk apartment for a bachelor with an eclectic taste for styles that span eras and archetypes â€“ the result is a mixture between the traditional and the ultramodern, carefully decorated w', 'portfolio/Se Jeong_20161205_181916_bachelor-bedroom-with-desk-inspiration.jpg', 'bachelor pad', 'sejeong@hotmail.com', 'A Beautiful One Bedroom Bachelor Apartment Under 100 Square Meters (With Floor Plan)', 'RM20000'),
(92, 'Designer and visualization artist Andrei Lychkouski designed this Minsk apartment for a bachelor with an eclectic taste for styles that span eras and archetypes â€“ the result is a mixture between the traditional and the ultramodern, carefully decorated w', 'portfolio/Se Jeong_20161205_181916_black-and-copper-kitchen-theme.jpg', 'bachelor pad', 'sejeong@hotmail.com', 'A Beautiful One Bedroom Bachelor Apartment Under 100 Square Meters (With Floor Plan)', 'RM20000'),
(93, 'Designer and visualization artist Andrei Lychkouski designed this Minsk apartment for a bachelor with an eclectic taste for styles that span eras and archetypes â€“ the result is a mixture between the traditional and the ultramodern, carefully decorated w', 'portfolio/Se Jeong_20161205_181916_black-kitchen-with-copper-backsplash.jpg', 'bachelor pad', 'sejeong@hotmail.com', 'A Beautiful One Bedroom Bachelor Apartment Under 100 Square Meters (With Floor Plan)', 'RM20000'),
(94, 'Designer and visualization artist Andrei Lychkouski designed this Minsk apartment for a bachelor with an eclectic taste for styles that span eras and archetypes â€“ the result is a mixture between the traditional and the ultramodern, carefully decorated w', 'portfolio/Se Jeong_20161205_181916_classic-decor-for-small-home.jpg', 'bachelor pad', 'sejeong@hotmail.com', 'A Beautiful One Bedroom Bachelor Apartment Under 100 Square Meters (With Floor Plan)', 'RM20000'),
(95, 'Designer and visualization artist Andrei Lychkouski designed this Minsk apartment for a bachelor with an eclectic taste for styles that span eras and archetypes â€“ the result is a mixture between the traditional and the ultramodern, carefully decorated w', 'portfolio/Se Jeong_20161205_181916_classic-door-for-modern-bathroom.jpg', 'bachelor pad', 'sejeong@hotmail.com', 'A Beautiful One Bedroom Bachelor Apartment Under 100 Square Meters (With Floor Plan)', 'RM20000'),
(96, 'Designer and visualization artist Andrei Lychkouski designed this Minsk apartment for a bachelor with an eclectic taste for styles that span eras and archetypes â€“ the result is a mixture between the traditional and the ultramodern, carefully decorated w', 'portfolio/Se Jeong_20161205_181916_copper-and-black-kitchen-theme.jpg', 'bachelor pad', 'sejeong@hotmail.com', 'A Beautiful One Bedroom Bachelor Apartment Under 100 Square Meters (With Floor Plan)', 'RM20000'),
(97, 'Designer and visualization artist Andrei Lychkouski designed this Minsk apartment for a bachelor with an eclectic taste for styles that span eras and archetypes â€“ the result is a mixture between the traditional and the ultramodern, carefully decorated w', 'portfolio/Se Jeong_20161205_181916_copper-and-grey-decor-theme.jpg', 'bachelor pad', 'sejeong@hotmail.com', 'A Beautiful One Bedroom Bachelor Apartment Under 100 Square Meters (With Floor Plan)', 'RM20000'),
(98, 'Designer and visualization artist Andrei Lychkouski designed this Minsk apartment for a bachelor with an eclectic taste for styles that span eras and archetypes â€“ the result is a mixture between the traditional and the ultramodern, carefully decorated w', 'portfolio/Se Jeong_20161205_181916_copper-and-seafoam-green-home-design-palette.jpg', 'bachelor pad', 'sejeong@hotmail.com', 'A Beautiful One Bedroom Bachelor Apartment Under 100 Square Meters (With Floor Plan)', 'RM20000'),
(99, 'Designer and visualization artist Andrei Lychkouski designed this Minsk apartment for a bachelor with an eclectic taste for styles that span eras and archetypes â€“ the result is a mixture between the traditional and the ultramodern, carefully decorated w', 'portfolio/Se Jeong_20161205_181916_copper-and-wood-kitchen.jpg', 'bachelor pad', 'sejeong@hotmail.com', 'A Beautiful One Bedroom Bachelor Apartment Under 100 Square Meters (With Floor Plan)', 'RM20000'),
(100, 'Designer and visualization artist Andrei Lychkouski designed this Minsk apartment for a bachelor with an eclectic taste for styles that span eras and archetypes â€“ the result is a mixture between the traditional and the ultramodern, carefully decorated w', 'portfolio/Se Jeong_20161205_181916_creative-bathroom-mirror-ideas.jpg', 'bachelor pad', 'sejeong@hotmail.com', 'A Beautiful One Bedroom Bachelor Apartment Under 100 Square Meters (With Floor Plan)', 'RM20000'),
(101, 'Designer and visualization artist Andrei Lychkouski designed this Minsk apartment for a bachelor with an eclectic taste for styles that span eras and archetypes â€“ the result is a mixture between the traditional and the ultramodern, carefully decorated w', 'portfolio/Se Jeong_20161205_181919_awesome-bookshelf-inspiration.jpg', 'bachelor pad', 'sejeong@hotmail.com', 'A Beautiful One Bedroom Bachelor Apartment Under 100 Square Meters (With Floor Plan)', 'RM20000'),
(102, 'Designer and visualization artist Andrei Lychkouski designed this Minsk apartment for a bachelor with an eclectic taste for styles that span eras and archetypes â€“ the result is a mixture between the traditional and the ultramodern, carefully decorated w', 'portfolio/Se Jeong_20161205_181919_bachelor-apartment-bathroom-design.jpg', 'bachelor pad', 'sejeong@hotmail.com', 'A Beautiful One Bedroom Bachelor Apartment Under 100 Square Meters (With Floor Plan)', 'RM20000'),
(103, 'Designer and visualization artist Andrei Lychkouski designed this Minsk apartment for a bachelor with an eclectic taste for styles that span eras and archetypes â€“ the result is a mixture between the traditional and the ultramodern, carefully decorated w', 'portfolio/Se Jeong_20161205_181919_bachelor-apartment-kitchen-design.jpg', 'bachelor pad', 'sejeong@hotmail.com', 'A Beautiful One Bedroom Bachelor Apartment Under 100 Square Meters (With Floor Plan)', 'RM20000'),
(104, 'Designer and visualization artist Andrei Lychkouski designed this Minsk apartment for a bachelor with an eclectic taste for styles that span eras and archetypes â€“ the result is a mixture between the traditional and the ultramodern, carefully decorated w', 'portfolio/Se Jeong_20161205_181919_bachelor-bedroom-with-desk-inspiration.jpg', 'bachelor pad', 'sejeong@hotmail.com', 'A Beautiful One Bedroom Bachelor Apartment Under 100 Square Meters (With Floor Plan)', 'RM20000'),
(105, 'Designer and visualization artist Andrei Lychkouski designed this Minsk apartment for a bachelor with an eclectic taste for styles that span eras and archetypes â€“ the result is a mixture between the traditional and the ultramodern, carefully decorated w', 'portfolio/Se Jeong_20161205_181919_black-and-copper-kitchen-theme.jpg', 'bachelor pad', 'sejeong@hotmail.com', 'A Beautiful One Bedroom Bachelor Apartment Under 100 Square Meters (With Floor Plan)', 'RM20000'),
(106, 'Designer and visualization artist Andrei Lychkouski designed this Minsk apartment for a bachelor with an eclectic taste for styles that span eras and archetypes â€“ the result is a mixture between the traditional and the ultramodern, carefully decorated w', 'portfolio/Se Jeong_20161205_181919_black-kitchen-with-copper-backsplash.jpg', 'bachelor pad', 'sejeong@hotmail.com', 'A Beautiful One Bedroom Bachelor Apartment Under 100 Square Meters (With Floor Plan)', 'RM20000'),
(107, 'Designer and visualization artist Andrei Lychkouski designed this Minsk apartment for a bachelor with an eclectic taste for styles that span eras and archetypes â€“ the result is a mixture between the traditional and the ultramodern, carefully decorated w', 'portfolio/Se Jeong_20161205_181919_classic-decor-for-small-home.jpg', 'bachelor pad', 'sejeong@hotmail.com', 'A Beautiful One Bedroom Bachelor Apartment Under 100 Square Meters (With Floor Plan)', 'RM20000'),
(108, 'Designer and visualization artist Andrei Lychkouski designed this Minsk apartment for a bachelor with an eclectic taste for styles that span eras and archetypes â€“ the result is a mixture between the traditional and the ultramodern, carefully decorated w', 'portfolio/Se Jeong_20161205_181919_classic-door-for-modern-bathroom.jpg', 'bachelor pad', 'sejeong@hotmail.com', 'A Beautiful One Bedroom Bachelor Apartment Under 100 Square Meters (With Floor Plan)', 'RM20000'),
(109, 'Designer and visualization artist Andrei Lychkouski designed this Minsk apartment for a bachelor with an eclectic taste for styles that span eras and archetypes â€“ the result is a mixture between the traditional and the ultramodern, carefully decorated w', 'portfolio/Se Jeong_20161205_181919_copper-and-black-kitchen-theme.jpg', 'bachelor pad', 'sejeong@hotmail.com', 'A Beautiful One Bedroom Bachelor Apartment Under 100 Square Meters (With Floor Plan)', 'RM20000'),
(110, 'Designer and visualization artist Andrei Lychkouski designed this Minsk apartment for a bachelor with an eclectic taste for styles that span eras and archetypes â€“ the result is a mixture between the traditional and the ultramodern, carefully decorated w', 'portfolio/Se Jeong_20161205_181919_copper-and-grey-decor-theme.jpg', 'bachelor pad', 'sejeong@hotmail.com', 'A Beautiful One Bedroom Bachelor Apartment Under 100 Square Meters (With Floor Plan)', 'RM20000'),
(111, 'Designer and visualization artist Andrei Lychkouski designed this Minsk apartment for a bachelor with an eclectic taste for styles that span eras and archetypes â€“ the result is a mixture between the traditional and the ultramodern, carefully decorated w', 'portfolio/Se Jeong_20161205_181919_copper-and-seafoam-green-home-design-palette.jpg', 'bachelor pad', 'sejeong@hotmail.com', 'A Beautiful One Bedroom Bachelor Apartment Under 100 Square Meters (With Floor Plan)', 'RM20000'),
(112, 'Designer and visualization artist Andrei Lychkouski designed this Minsk apartment for a bachelor with an eclectic taste for styles that span eras and archetypes â€“ the result is a mixture between the traditional and the ultramodern, carefully decorated w', 'portfolio/Se Jeong_20161205_181919_copper-and-wood-kitchen.jpg', 'bachelor pad', 'sejeong@hotmail.com', 'A Beautiful One Bedroom Bachelor Apartment Under 100 Square Meters (With Floor Plan)', 'RM20000'),
(113, 'Designer and visualization artist Andrei Lychkouski designed this Minsk apartment for a bachelor with an eclectic taste for styles that span eras and archetypes â€“ the result is a mixture between the traditional and the ultramodern, carefully decorated w', 'portfolio/Se Jeong_20161205_181919_creative-bathroom-mirror-ideas.jpg', 'bachelor pad', 'sejeong@hotmail.com', 'A Beautiful One Bedroom Bachelor Apartment Under 100 Square Meters (With Floor Plan)', 'RM20000'),
(114, 'Designer and visualization artist Andrei Lychkouski designed this Minsk apartment for a bachelor with an eclectic taste for styles that span eras and archetypes â€“ the result is a mixture between the traditional and the ultramodern, carefully decorated w', 'portfolio/Se Jeong_20161205_181939_awesome-bookshelf-inspiration.jpg', 'bachelor pad', 'sejeong@hotmail.com', 'A Beautiful One Bedroom Bachelor Apartment Under 100 Square Meters (With Floor Plan)', 'RM20000'),
(115, 'Designer and visualization artist Andrei Lychkouski designed this Minsk apartment for a bachelor with an eclectic taste for styles that span eras and archetypes â€“ the result is a mixture between the traditional and the ultramodern, carefully decorated w', 'portfolio/Se Jeong_20161205_181939_bachelor-apartment-bathroom-design.jpg', 'bachelor pad', 'sejeong@hotmail.com', 'A Beautiful One Bedroom Bachelor Apartment Under 100 Square Meters (With Floor Plan)', 'RM20000'),
(116, 'Designer and visualization artist Andrei Lychkouski designed this Minsk apartment for a bachelor with an eclectic taste for styles that span eras and archetypes â€“ the result is a mixture between the traditional and the ultramodern, carefully decorated w', 'portfolio/Se Jeong_20161205_181939_bachelor-apartment-kitchen-design.jpg', 'bachelor pad', 'sejeong@hotmail.com', 'A Beautiful One Bedroom Bachelor Apartment Under 100 Square Meters (With Floor Plan)', 'RM20000'),
(117, 'Designer and visualization artist Andrei Lychkouski designed this Minsk apartment for a bachelor with an eclectic taste for styles that span eras and archetypes â€“ the result is a mixture between the traditional and the ultramodern, carefully decorated w', 'portfolio/Se Jeong_20161205_181939_bachelor-bedroom-with-desk-inspiration.jpg', 'bachelor pad', 'sejeong@hotmail.com', 'A Beautiful One Bedroom Bachelor Apartment Under 100 Square Meters (With Floor Plan)', 'RM20000'),
(118, 'Designer and visualization artist Andrei Lychkouski designed this Minsk apartment for a bachelor with an eclectic taste for styles that span eras and archetypes â€“ the result is a mixture between the traditional and the ultramodern, carefully decorated w', 'portfolio/Se Jeong_20161205_181939_black-and-copper-kitchen-theme.jpg', 'bachelor pad', 'sejeong@hotmail.com', 'A Beautiful One Bedroom Bachelor Apartment Under 100 Square Meters (With Floor Plan)', 'RM20000'),
(119, 'Designer and visualization artist Andrei Lychkouski designed this Minsk apartment for a bachelor with an eclectic taste for styles that span eras and archetypes â€“ the result is a mixture between the traditional and the ultramodern, carefully decorated w', 'portfolio/Se Jeong_20161205_181939_black-kitchen-with-copper-backsplash.jpg', 'bachelor pad', 'sejeong@hotmail.com', 'A Beautiful One Bedroom Bachelor Apartment Under 100 Square Meters (With Floor Plan)', 'RM20000'),
(120, 'Designer and visualization artist Andrei Lychkouski designed this Minsk apartment for a bachelor with an eclectic taste for styles that span eras and archetypes â€“ the result is a mixture between the traditional and the ultramodern, carefully decorated w', 'portfolio/Se Jeong_20161205_181939_classic-decor-for-small-home.jpg', 'bachelor pad', 'sejeong@hotmail.com', 'A Beautiful One Bedroom Bachelor Apartment Under 100 Square Meters (With Floor Plan)', 'RM20000'),
(121, 'Designer and visualization artist Andrei Lychkouski designed this Minsk apartment for a bachelor with an eclectic taste for styles that span eras and archetypes â€“ the result is a mixture between the traditional and the ultramodern, carefully decorated w', 'portfolio/Se Jeong_20161205_181939_classic-door-for-modern-bathroom.jpg', 'bachelor pad', 'sejeong@hotmail.com', 'A Beautiful One Bedroom Bachelor Apartment Under 100 Square Meters (With Floor Plan)', 'RM20000'),
(122, 'Designer and visualization artist Andrei Lychkouski designed this Minsk apartment for a bachelor with an eclectic taste for styles that span eras and archetypes â€“ the result is a mixture between the traditional and the ultramodern, carefully decorated w', 'portfolio/Se Jeong_20161205_181939_copper-and-black-kitchen-theme.jpg', 'bachelor pad', 'sejeong@hotmail.com', 'A Beautiful One Bedroom Bachelor Apartment Under 100 Square Meters (With Floor Plan)', 'RM20000'),
(123, 'Designer and visualization artist Andrei Lychkouski designed this Minsk apartment for a bachelor with an eclectic taste for styles that span eras and archetypes â€“ the result is a mixture between the traditional and the ultramodern, carefully decorated w', 'portfolio/Se Jeong_20161205_181939_copper-and-grey-decor-theme.jpg', 'bachelor pad', 'sejeong@hotmail.com', 'A Beautiful One Bedroom Bachelor Apartment Under 100 Square Meters (With Floor Plan)', 'RM20000'),
(124, 'Designer and visualization artist Andrei Lychkouski designed this Minsk apartment for a bachelor with an eclectic taste for styles that span eras and archetypes â€“ the result is a mixture between the traditional and the ultramodern, carefully decorated w', 'portfolio/Se Jeong_20161205_181939_copper-and-seafoam-green-home-design-palette.jpg', 'bachelor pad', 'sejeong@hotmail.com', 'A Beautiful One Bedroom Bachelor Apartment Under 100 Square Meters (With Floor Plan)', 'RM20000'),
(125, 'Designer and visualization artist Andrei Lychkouski designed this Minsk apartment for a bachelor with an eclectic taste for styles that span eras and archetypes â€“ the result is a mixture between the traditional and the ultramodern, carefully decorated w', 'portfolio/Se Jeong_20161205_181939_copper-and-wood-kitchen.jpg', 'bachelor pad', 'sejeong@hotmail.com', 'A Beautiful One Bedroom Bachelor Apartment Under 100 Square Meters (With Floor Plan)', 'RM20000'),
(126, 'Designer and visualization artist Andrei Lychkouski designed this Minsk apartment for a bachelor with an eclectic taste for styles that span eras and archetypes â€“ the result is a mixture between the traditional and the ultramodern, carefully decorated w', 'portfolio/Se Jeong_20161205_181939_creative-bathroom-mirror-ideas.jpg', 'bachelor pad', 'sejeong@hotmail.com', 'A Beautiful One Bedroom Bachelor Apartment Under 100 Square Meters (With Floor Plan)', 'RM20000'),
(127, 'We all have quirks and luxuries we would love to indulge. Yet agate doesnâ€™t always work with interiors, emojis donâ€™t always light up your kitchen, and marble and slate make for expensive kitchen benchtops. Create it in a coaster instead? Problem solve', 'portfolio/So Hye_20161205_182139_3D-illusion-printed-coasters-600x600.jpg', 'accessories, dining', 'sohye@hotmail.com', '52 Unique Drink Coasters To Help You Keep Your Stains Off In Style', '12'),
(128, 'We all have quirks and luxuries we would love to indulge. Yet agate doesnâ€™t always work with interiors, emojis donâ€™t always light up your kitchen, and marble and slate make for expensive kitchen benchtops. Create it in a coaster instead? Problem solve', 'portfolio/So Hye_20161205_182139_brain-particle-glass-coasters-600x600.jpeg', 'accessories, dining', 'sohye@hotmail.com', '52 Unique Drink Coasters To Help You Keep Your Stains Off In Style', '12'),
(129, 'We all have quirks and luxuries we would love to indulge. Yet agate doesnâ€™t always work with interiors, emojis donâ€™t always light up your kitchen, and marble and slate make for expensive kitchen benchtops. Create it in a coaster instead? Problem solve', 'portfolio/So Hye_20161205_182139_bullet-cap-metal-coasters-600x600.jpg', 'accessories, dining', 'sohye@hotmail.com', '52 Unique Drink Coasters To Help You Keep Your Stains Off In Style', '12'),
(130, 'We all have quirks and luxuries we would love to indulge. Yet agate doesnâ€™t always work with interiors, emojis donâ€™t always light up your kitchen, and marble and slate make for expensive kitchen benchtops. Create it in a coaster instead? Problem solve', 'portfolio/So Hye_20161205_182139_central-feature-custom-paper-coasters-600x466.jpg', 'accessories, dining', 'sohye@hotmail.com', '52 Unique Drink Coasters To Help You Keep Your Stains Off In Style', '12'),
(131, 'We all have quirks and luxuries we would love to indulge. Yet agate doesnâ€™t always work with interiors, emojis donâ€™t always light up your kitchen, and marble and slate make for expensive kitchen benchtops. Create it in a coaster instead? Problem solve', 'portfolio/So Hye_20161205_182139_cerated-tin-edge-metal-coasters-600x382.jpg', 'accessories, dining', 'sohye@hotmail.com', '52 Unique Drink Coasters To Help You Keep Your Stains Off In Style', '12'),
(132, 'We all have quirks and luxuries we would love to indulge. Yet agate doesnâ€™t always work with interiors, emojis donâ€™t always light up your kitchen, and marble and slate make for expensive kitchen benchtops. Create it in a coaster instead? Problem solve', 'portfolio/So Hye_20161205_182139_coloured-gradient-stone-coasters-600x415.jpg', 'accessories, dining', 'sohye@hotmail.com', '52 Unique Drink Coasters To Help You Keep Your Stains Off In Style', '12'),
(133, 'We all have quirks and luxuries we would love to indulge. Yet agate doesnâ€™t always work with interiors, emojis donâ€™t always light up your kitchen, and marble and slate make for expensive kitchen benchtops. Create it in a coaster instead? Problem solve', 'portfolio/So Hye_20161205_182139_colourful-agate-coasters-600x391.jpg', 'accessories, dining', 'sohye@hotmail.com', '52 Unique Drink Coasters To Help You Keep Your Stains Off In Style', '12'),
(134, 'We all have quirks and luxuries we would love to indulge. Yet agate doesnâ€™t always work with interiors, emojis donâ€™t always light up your kitchen, and marble and slate make for expensive kitchen benchtops. Create it in a coaster instead? Problem solve', 'portfolio/So Hye_20161205_182139_colourful-emoji-printed-coasters-600x513.jpg', 'accessories, dining', 'sohye@hotmail.com', '52 Unique Drink Coasters To Help You Keep Your Stains Off In Style', '12'),
(135, 'We all have quirks and luxuries we would love to indulge. Yet agate doesnâ€™t always work with interiors, emojis donâ€™t always light up your kitchen, and marble and slate make for expensive kitchen benchtops. Create it in a coaster instead? Problem solve', 'portfolio/So Hye_20161205_182139_concrete-and-wooden-heart-custom-coasters-600x400.jpg', 'accessories, dining', 'sohye@hotmail.com', '52 Unique Drink Coasters To Help You Keep Your Stains Off In Style', '12'),
(136, 'We all have quirks and luxuries we would love to indulge. Yet agate doesnâ€™t always work with interiors, emojis donâ€™t always light up your kitchen, and marble and slate make for expensive kitchen benchtops. Create it in a coaster instead? Problem solve', 'portfolio/So Hye_20161205_182139_cream-and-gold-panel-cup-coaster-600x600.jpg', 'accessories, dining', 'sohye@hotmail.com', '52 Unique Drink Coasters To Help You Keep Your Stains Off In Style', '12'),
(137, 'We all have quirks and luxuries we would love to indulge. Yet agate doesnâ€™t always work with interiors, emojis donâ€™t always light up your kitchen, and marble and slate make for expensive kitchen benchtops. Create it in a coaster instead? Problem solve', 'portfolio/So Hye_20161205_182139_cut-out-cute-animal-wood-coasters-600x600.jpeg', 'accessories, dining', 'sohye@hotmail.com', '52 Unique Drink Coasters To Help You Keep Your Stains Off In Style', '12'),
(138, 'We all have quirks and luxuries we would love to indulge. Yet agate doesnâ€™t always work with interiors, emojis donâ€™t always light up your kitchen, and marble and slate make for expensive kitchen benchtops. Create it in a coaster instead? Problem solve', 'portfolio/So Hye_20161205_182139_differing-colour-wooden-cool-drink-coasters-600x400.jpg', 'accessories, dining', 'sohye@hotmail.com', '52 Unique Drink Coasters To Help You Keep Your Stains Off In Style', '12'),
(139, 'Black and white interiors are impossible to ignore. They''re bold, versatile, and perhaps most importantly, they always allow the interesting architectural elements and fixtures to stand at center stage. This post covers 40 amazing kitchens that use greysc', 'portfolio/So Hye_20161205_182310_black-and-white-kitchen-inspiration.jpg', ' black, black and white', 'sohye@hotmail.com', '40 Beautiful Black and White Kitchen Designs', 'RM20000'),
(140, 'Black and white interiors are impossible to ignore. They''re bold, versatile, and perhaps most importantly, they always allow the interesting architectural elements and fixtures to stand at center stage. This post covers 40 amazing kitchens that use greysc', 'portfolio/So Hye_20161205_182310_black-and-white-kitchen-with-marble-floor.jpg', ' black, black and white', 'sohye@hotmail.com', '40 Beautiful Black and White Kitchen Designs', 'RM20000'),
(141, 'Black and white interiors are impossible to ignore. They''re bold, versatile, and perhaps most importantly, they always allow the interesting architectural elements and fixtures to stand at center stage. This post covers 40 amazing kitchens that use greysc', 'portfolio/So Hye_20161205_182310_black-chevron-floors-in-kitchen.jpg', ' black, black and white', 'sohye@hotmail.com', '40 Beautiful Black and White Kitchen Designs', 'RM20000'),
(142, 'Black and white interiors are impossible to ignore. They''re bold, versatile, and perhaps most importantly, they always allow the interesting architectural elements and fixtures to stand at center stage. This post covers 40 amazing kitchens that use greysc', 'portfolio/So Hye_20161205_182310_black-on-black-kitchen-with-vertical-garden.jpg', ' black, black and white', 'sohye@hotmail.com', '40 Beautiful Black and White Kitchen Designs', 'RM20000'),
(143, 'Black and white interiors are impossible to ignore. They''re bold, versatile, and perhaps most importantly, they always allow the interesting architectural elements and fixtures to stand at center stage. This post covers 40 amazing kitchens that use greysc', 'portfolio/So Hye_20161205_182310_color-blocking-in-black-and-white-kitchen-dining-combination.jpg', ' black, black and white', 'sohye@hotmail.com', '40 Beautiful Black and White Kitchen Designs', 'RM20000'),
(144, 'Black and white interiors are impossible to ignore. They''re bold, versatile, and perhaps most importantly, they always allow the interesting architectural elements and fixtures to stand at center stage. This post covers 40 amazing kitchens that use greysc', 'portfolio/So Hye_20161205_182310_geometric-greyscale-kitchen.jpg', ' black, black and white', 'sohye@hotmail.com', '40 Beautiful Black and White Kitchen Designs', 'RM20000'),
(145, 'Black and white interiors are impossible to ignore. They''re bold, versatile, and perhaps most importantly, they always allow the interesting architectural elements and fixtures to stand at center stage. This post covers 40 amazing kitchens that use greysc', 'portfolio/So Hye_20161205_182310_glossy-white-kitchen-cabinets-with-matte-backsplash.jpg', ' black, black and white', 'sohye@hotmail.com', '40 Beautiful Black and White Kitchen Designs', 'RM20000'),
(146, 'Black and white interiors are impossible to ignore. They''re bold, versatile, and perhaps most importantly, they always allow the interesting architectural elements and fixtures to stand at center stage. This post covers 40 amazing kitchens that use greysc', 'portfolio/So Hye_20161205_182310_greyscale-kitchen-with-neutral-wood-cabinets.jpg', ' black, black and white', 'sohye@hotmail.com', '40 Beautiful Black and White Kitchen Designs', 'RM20000'),
(147, 'Black and white interiors are impossible to ignore. They''re bold, versatile, and perhaps most importantly, they always allow the interesting architectural elements and fixtures to stand at center stage. This post covers 40 amazing kitchens that use greysc', 'portfolio/So Hye_20161205_182310_greyscale-kitchen-with-potted-plants.jpg', ' black, black and white', 'sohye@hotmail.com', '40 Beautiful Black and White Kitchen Designs', 'RM20000'),
(148, 'Black and white interiors are impossible to ignore. They''re bold, versatile, and perhaps most importantly, they always allow the interesting architectural elements and fixtures to stand at center stage. This post covers 40 amazing kitchens that use greysc', 'portfolio/So Hye_20161205_182310_matte-black-and-copper-kitchen.jpg', ' black, black and white', 'sohye@hotmail.com', '40 Beautiful Black and White Kitchen Designs', 'RM20000'),
(149, 'Black and white interiors are impossible to ignore. They''re bold, versatile, and perhaps most importantly, they always allow the interesting architectural elements and fixtures to stand at center stage. This post covers 40 amazing kitchens that use greysc', 'portfolio/So Hye_20161205_182310_minimalist-black-and-white-kitchen-design.jpg', ' black, black and white', 'sohye@hotmail.com', '40 Beautiful Black and White Kitchen Designs', 'RM20000'),
(150, 'Black and white interiors are impossible to ignore. They''re bold, versatile, and perhaps most importantly, they always allow the interesting architectural elements and fixtures to stand at center stage. This post covers 40 amazing kitchens that use greysc', 'portfolio/So Hye_20161205_182310_modern-neutral-kitchen-with-window-backsplash.jpg', ' black, black and white', 'sohye@hotmail.com', '40 Beautiful Black and White Kitchen Designs', 'RM20000'),
(151, 'Black and white interiors are impossible to ignore. They''re bold, versatile, and perhaps most importantly, they always allow the interesting architectural elements and fixtures to stand at center stage. This post covers 40 amazing kitchens that use greysc', 'portfolio/So Hye_20161205_182310_ultra-minimalist-black-and-white-kitchen-inspiration.jpg', ' black, black and white', 'sohye@hotmail.com', '40 Beautiful Black and White Kitchen Designs', 'RM20000'),
(152, 'Black and white interiors are impossible to ignore. They''re bold, versatile, and perhaps most importantly, they always allow the interesting architectural elements and fixtures to stand at center stage. This post covers 40 amazing kitchens that use greysc', 'portfolio/So Hye_20161205_182310_unique-black-kitchen-island-and-bar-combination.jpg', ' black, black and white', 'sohye@hotmail.com', '40 Beautiful Black and White Kitchen Designs', 'RM20000'),
(153, 'Black and white interiors are impossible to ignore. They''re bold, versatile, and perhaps most importantly, they always allow the interesting architectural elements and fixtures to stand at center stage. This post covers 40 amazing kitchens that use greysc', 'portfolio/So Hye_20161205_182310_wood-island-in-black-and-white-kitchen.jpg', ' black, black and white', 'sohye@hotmail.com', '40 Beautiful Black and White Kitchen Designs', 'RM20000'),
(154, 'A small apartment need not obstruct style. These four spaces under 100sqm create characterful and contemporary living areas. White walls meet light wood with artistic, calligraphed wall decals. Dark, dangerous colours meet slate flooring and street lighti', 'portfolio/So Hye_20161205_182452_beige-wall-quote-small-minimalist-apartment.jpg', ' small space', 'sohye@hotmail.com', '4 Small Apartment Interiors Embracing Character Themes', 'RM20000'),
(155, 'A small apartment need not obstruct style. These four spaces under 100sqm create characterful and contemporary living areas. White walls meet light wood with artistic, calligraphed wall decals. Dark, dangerous colours meet slate flooring and street lighti', 'portfolio/So Hye_20161205_182452_corridor-kitchen-small-white-apartment.jpg', ' small space', 'sohye@hotmail.com', '4 Small Apartment Interiors Embracing Character Themes', 'RM20000'),
(156, 'A small apartment need not obstruct style. These four spaces under 100sqm create characterful and contemporary living areas. White walls meet light wood with artistic, calligraphed wall decals. Dark, dangerous colours meet slate flooring and street lighti', 'portfolio/So Hye_20161205_182452_draped-idea-lighting-small-minimalist-apartment.jpg', ' small space', 'sohye@hotmail.com', '4 Small Apartment Interiors Embracing Character Themes', 'RM20000'),
(157, 'A small apartment need not obstruct style. These four spaces under 100sqm create characterful and contemporary living areas. White walls meet light wood with artistic, calligraphed wall decals. Dark, dangerous colours meet slate flooring and street lighti', 'portfolio/So Hye_20161205_182452_extended-bench-dining-area-small-minimal-apartment.jpg', ' small space', 'sohye@hotmail.com', '4 Small Apartment Interiors Embracing Character Themes', 'RM20000'),
(158, 'A small apartment need not obstruct style. These four spaces under 100sqm create characterful and contemporary living areas. White walls meet light wood with artistic, calligraphed wall decals. Dark, dangerous colours meet slate flooring and street lighti', 'portfolio/So Hye_20161205_182452_geometric-feature-wall-small-white-apartment.jpg', ' small space', 'sohye@hotmail.com', '4 Small Apartment Interiors Embracing Character Themes', 'RM20000'),
(159, 'A small apartment need not obstruct style. These four spaces under 100sqm create characterful and contemporary living areas. White walls meet light wood with artistic, calligraphed wall decals. Dark, dangerous colours meet slate flooring and street lighti', 'portfolio/So Hye_20161205_182452_light-and-bright-living-room-small-apartment.jpg', ' small space', 'sohye@hotmail.com', '4 Small Apartment Interiors Embracing Character Themes', 'RM20000'),
(160, 'A small apartment need not obstruct style. These four spaces under 100sqm create characterful and contemporary living areas. White walls meet light wood with artistic, calligraphed wall decals. Dark, dangerous colours meet slate flooring and street lighti', 'portfolio/So Hye_20161205_182452_light-and-bright-white-minimalist-apartment.jpg', ' small space', 'sohye@hotmail.com', '4 Small Apartment Interiors Embracing Character Themes', 'RM20000');
INSERT INTO `portfolio` (`id`, `description`, `picture`, `tags`, `userid`, `title`, `price`) VALUES
(161, 'A small apartment need not obstruct style. These four spaces under 100sqm create characterful and contemporary living areas. White walls meet light wood with artistic, calligraphed wall decals. Dark, dangerous colours meet slate flooring and street lighti', 'portfolio/So Hye_20161205_182452_muted-rainbow-bedroom-small-minimalist-apartment.jpg', ' small space', 'sohye@hotmail.com', '4 Small Apartment Interiors Embracing Character Themes', 'RM20000'),
(162, 'A small apartment need not obstruct style. These four spaces under 100sqm create characterful and contemporary living areas. White walls meet light wood with artistic, calligraphed wall decals. Dark, dangerous colours meet slate flooring and street lighti', 'portfolio/So Hye_20161205_182452_small-apartment-white-dining-area.jpg', ' small space', 'sohye@hotmail.com', '4 Small Apartment Interiors Embracing Character Themes', 'RM20000'),
(163, 'A small apartment need not obstruct style. These four spaces under 100sqm create characterful and contemporary living areas. White walls meet light wood with artistic, calligraphed wall decals. Dark, dangerous colours meet slate flooring and street lighti', 'portfolio/So Hye_20161205_182452_white-dividing-panel-minimalist-apartment.jpg', ' small space', 'sohye@hotmail.com', '4 Small Apartment Interiors Embracing Character Themes', 'RM20000'),
(164, 'Minimalism has long been a popular look for social areas of the home, but the rising popularity of low-profile beds and greyscale color palettes indicates that minimalist bedrooms are catching up quickly. And for good reason! This philosophy streamlines b', 'portfolio/So Hye_20161205_182612_bedroom-with-cute-minimalist-decor.jpg', ' bedroom,minimalist', 'sohye@hotmail.com', '40 Serenely Minimalist Bedrooms To Help You Embrace Simple Comforts', 'RM20000'),
(165, 'Minimalism has long been a popular look for social areas of the home, but the rising popularity of low-profile beds and greyscale color palettes indicates that minimalist bedrooms are catching up quickly. And for good reason! This philosophy streamlines b', 'portfolio/So Hye_20161205_182612_industrial-bedroom-without-concrete.jpg', ' bedroom,minimalist', 'sohye@hotmail.com', '40 Serenely Minimalist Bedrooms To Help You Embrace Simple Comforts', 'RM20000'),
(166, 'Minimalism has long been a popular look for social areas of the home, but the rising popularity of low-profile beds and greyscale color palettes indicates that minimalist bedrooms are catching up quickly. And for good reason! This philosophy streamlines b', 'portfolio/So Hye_20161205_182612_minimalist-bedroom-design-ideas.jpg', ' bedroom,minimalist', 'sohye@hotmail.com', '40 Serenely Minimalist Bedrooms To Help You Embrace Simple Comforts', 'RM20000'),
(167, 'Minimalism has long been a popular look for social areas of the home, but the rising popularity of low-profile beds and greyscale color palettes indicates that minimalist bedrooms are catching up quickly. And for good reason! This philosophy streamlines b', 'portfolio/So Hye_20161205_182612_minimalist-bedroom-with-a-view.jpeg', ' bedroom,minimalist', 'sohye@hotmail.com', '40 Serenely Minimalist Bedrooms To Help You Embrace Simple Comforts', 'RM20000'),
(168, 'Minimalism has long been a popular look for social areas of the home, but the rising popularity of low-profile beds and greyscale color palettes indicates that minimalist bedrooms are catching up quickly. And for good reason! This philosophy streamlines b', 'portfolio/So Hye_20161205_182612_minimalist-bedroom-with-concrete-accents.jpg', ' bedroom,minimalist', 'sohye@hotmail.com', '40 Serenely Minimalist Bedrooms To Help You Embrace Simple Comforts', 'RM20000'),
(169, 'Minimalism has long been a popular look for social areas of the home, but the rising popularity of low-profile beds and greyscale color palettes indicates that minimalist bedrooms are catching up quickly. And for good reason! This philosophy streamlines b', 'portfolio/So Hye_20161205_182612_minimalist-color-palettes-for-the-bedroom.jpg', ' bedroom,minimalist', 'sohye@hotmail.com', '40 Serenely Minimalist Bedrooms To Help You Embrace Simple Comforts', 'RM20000'),
(170, 'Minimalism has long been a popular look for social areas of the home, but the rising popularity of low-profile beds and greyscale color palettes indicates that minimalist bedrooms are catching up quickly. And for good reason! This philosophy streamlines b', 'portfolio/So Hye_20161205_182612_natural-minimalist-bedroom.jpg', ' bedroom,minimalist', 'sohye@hotmail.com', '40 Serenely Minimalist Bedrooms To Help You Embrace Simple Comforts', 'RM20000'),
(171, 'Minimalism has long been a popular look for social areas of the home, but the rising popularity of low-profile beds and greyscale color palettes indicates that minimalist bedrooms are catching up quickly. And for good reason! This philosophy streamlines b', 'portfolio/So Hye_20161205_182612_natural-neutral-bedroom-color-scheme.jpg', ' bedroom,minimalist', 'sohye@hotmail.com', '40 Serenely Minimalist Bedrooms To Help You Embrace Simple Comforts', 'RM20000'),
(172, 'Minimalism has long been a popular look for social areas of the home, but the rising popularity of low-profile beds and greyscale color palettes indicates that minimalist bedrooms are catching up quickly. And for good reason! This philosophy streamlines b', 'portfolio/So Hye_20161205_182612_relaxing-simple-bedroom-design.jpg', ' bedroom,minimalist', 'sohye@hotmail.com', '40 Serenely Minimalist Bedrooms To Help You Embrace Simple Comforts', 'RM20000'),
(173, 'Minimalism has long been a popular look for social areas of the home, but the rising popularity of low-profile beds and greyscale color palettes indicates that minimalist bedrooms are catching up quickly. And for good reason! This philosophy streamlines b', 'portfolio/So Hye_20161205_182612_using-art-in-minimalist-bedrooms.jpg', ' bedroom,minimalist', 'sohye@hotmail.com', '40 Serenely Minimalist Bedrooms To Help You Embrace Simple Comforts', 'RM20000'),
(174, 'Every interior can benefit from warm, wooden tones to fire up those cold winter nights. What better way to inject the rustic than with a wooden wall clock? Themed, Scandinavian, unbranded or for the kids, these thirty-four clocks add interest and a smile ', 'portfolio/nayoung_20161205_182745_hexagon-painted-decorative-wooden-wall-clocks-600x1197 (1).jpg', 'clocks,wood interior', 'nayoung@hotmail.com', '34 Wooden Wall Clocks To Warm Up Your Interior', 'RM20000'),
(175, 'Every interior can benefit from warm, wooden tones to fire up those cold winter nights. What better way to inject the rustic than with a wooden wall clock? Themed, Scandinavian, unbranded or for the kids, these thirty-four clocks add interest and a smile ', 'portfolio/nayoung_20161205_182745_hexagon-painted-decorative-wooden-wall-clocks-600x1197.jpg', 'clocks,wood interior', 'nayoung@hotmail.com', '34 Wooden Wall Clocks To Warm Up Your Interior', 'RM20000'),
(176, 'Every interior can benefit from warm, wooden tones to fire up those cold winter nights. What better way to inject the rustic than with a wooden wall clock? Themed, Scandinavian, unbranded or for the kids, these thirty-four clocks add interest and a smile ', 'portfolio/nayoung_20161205_182745_leather-strap-hanging-wooden-clocks-600x900.jpg', 'clocks,wood interior', 'nayoung@hotmail.com', '34 Wooden Wall Clocks To Warm Up Your Interior', 'RM20000'),
(177, 'Every interior can benefit from warm, wooden tones to fire up those cold winter nights. What better way to inject the rustic than with a wooden wall clock? Themed, Scandinavian, unbranded or for the kids, these thirty-four clocks add interest and a smile ', 'portfolio/nayoung_20161205_182745_modern-design-wood-and-concrete-clocks-600x1376.jpg', 'clocks,wood interior', 'nayoung@hotmail.com', '34 Wooden Wall Clocks To Warm Up Your Interior', 'RM20000'),
(178, 'Every interior can benefit from warm, wooden tones to fire up those cold winter nights. What better way to inject the rustic than with a wooden wall clock? Themed, Scandinavian, unbranded or for the kids, these thirty-four clocks add interest and a smile ', 'portfolio/nayoung_20161205_182745_new-york-new-delhi-paris-wooden-wall-clocks-uk-600x1493 (1).jpg', 'clocks,wood interior', 'nayoung@hotmail.com', '34 Wooden Wall Clocks To Warm Up Your Interior', 'RM20000'),
(179, 'Every interior can benefit from warm, wooden tones to fire up those cold winter nights. What better way to inject the rustic than with a wooden wall clock? Themed, Scandinavian, unbranded or for the kids, these thirty-four clocks add interest and a smile ', 'portfolio/nayoung_20161205_182745_new-york-new-delhi-paris-wooden-wall-clocks-uk-600x1493.jpg', 'clocks,wood interior', 'nayoung@hotmail.com', '34 Wooden Wall Clocks To Warm Up Your Interior', 'RM20000'),
(180, 'Every interior can benefit from warm, wooden tones to fire up those cold winter nights. What better way to inject the rustic than with a wooden wall clock? Themed, Scandinavian, unbranded or for the kids, these thirty-four clocks add interest and a smile ', 'portfolio/nayoung_20161205_182745_pie-slice-painted-white-wooden-wall-clocks-online-shopping-600x450.jpg', 'clocks,wood interior', 'nayoung@hotmail.com', '34 Wooden Wall Clocks To Warm Up Your Interior', 'RM20000'),
(181, 'Often used in bedroom design, the soft appeal of grey can cool many interiors. Yet one secret power remains - its subtle transformation of kitchens. Often left in the cold for warmer wooden tones, its ability to make a kitchen look fresh and contemporary ', 'portfolio/nayoung_20161205_183024_all-grey-kitchen-contemporary-white-peonies.jpg', 'grey,kitchen,modern', 'nayoung@hotmail.com', '40 Gorgeous Grey Kitchens', 'RM20000'),
(182, 'Often used in bedroom design, the soft appeal of grey can cool many interiors. Yet one secret power remains - its subtle transformation of kitchens. Often left in the cold for warmer wooden tones, its ability to make a kitchen look fresh and contemporary ', 'portfolio/nayoung_20161205_183024_light-grey-and-white-kitchen-open-plan.jpg', 'grey,kitchen,modern', 'nayoung@hotmail.com', '40 Gorgeous Grey Kitchens', 'RM20000'),
(183, 'Often used in bedroom design, the soft appeal of grey can cool many interiors. Yet one secret power remains - its subtle transformation of kitchens. Often left in the cold for warmer wooden tones, its ability to make a kitchen look fresh and contemporary ', 'portfolio/nayoung_20161205_183024_light-grey-and-white-kitchen-wine-glass-lighting.jpg', 'grey,kitchen,modern', 'nayoung@hotmail.com', '40 Gorgeous Grey Kitchens', 'RM20000'),
(184, 'Often used in bedroom design, the soft appeal of grey can cool many interiors. Yet one secret power remains - its subtle transformation of kitchens. Often left in the cold for warmer wooden tones, its ability to make a kitchen look fresh and contemporary ', 'portfolio/nayoung_20161205_183024_mid-grey-and-white-kitchen-wooden-floor.jpg', 'grey,kitchen,modern', 'nayoung@hotmail.com', '40 Gorgeous Grey Kitchens', 'RM20000'),
(185, 'Often used in bedroom design, the soft appeal of grey can cool many interiors. Yet one secret power remains - its subtle transformation of kitchens. Often left in the cold for warmer wooden tones, its ability to make a kitchen look fresh and contemporary ', 'portfolio/nayoung_20161205_183024_teal-and-grey-kitchen-teal-hanging-lights.jpg', 'grey,kitchen,modern', 'nayoung@hotmail.com', '40 Gorgeous Grey Kitchens', 'RM20000'),
(186, 'Often used in bedroom design, the soft appeal of grey can cool many interiors. Yet one secret power remains - its subtle transformation of kitchens. Often left in the cold for warmer wooden tones, its ability to make a kitchen look fresh and contemporary ', 'portfolio/nayoung_20161205_183024_tetris-style-kitchen-mid-grey-sloping-window.jpg', 'grey,kitchen,modern', 'nayoung@hotmail.com', '40 Gorgeous Grey Kitchens', 'RM20000'),
(187, 'Often used in bedroom design, the soft appeal of grey can cool many interiors. Yet one secret power remains - its subtle transformation of kitchens. Often left in the cold for warmer wooden tones, its ability to make a kitchen look fresh and contemporary ', 'portfolio/nayoung_20161205_183024_white-and-grey-kitchen-bauble-lighting.jpg', 'grey,kitchen,modern', 'nayoung@hotmail.com', '40 Gorgeous Grey Kitchens', 'RM20000'),
(188, 'With many design influences springing from the West â€“ Nordic, Scandinavian, French â€“ we sometimes forget about the luxuries of the East. Simplistic with a taste of a different kind of rustic, they offer modern elegance with a twist. Lush plant life jo', 'portfolio/nayoung_20161205_183121_Asian-industrial-living-room-iron-hanging-lights.jpg', 'asian,modern,scandinavian', 'nayoung@hotmail.com', '4 Asian-Influenced Interiors That Exude the East', 'RM20000'),
(189, 'With many design influences springing from the West â€“ Nordic, Scandinavian, French â€“ we sometimes forget about the luxuries of the East. Simplistic with a taste of a different kind of rustic, they offer modern elegance with a twist. Lush plant life jo', 'portfolio/nayoung_20161205_183121_Asian-living-room-boxed-white-windows-concrete-flooring.jpg', 'asian,modern,scandinavian', 'nayoung@hotmail.com', '4 Asian-Influenced Interiors That Exude the East', 'RM20000'),
(190, 'With many design influences springing from the West â€“ Nordic, Scandinavian, French â€“ we sometimes forget about the luxuries of the East. Simplistic with a taste of a different kind of rustic, they offer modern elegance with a twist. Lush plant life jo', 'portfolio/nayoung_20161205_183121_modern-jungle-living-room-brown-leather-sofa-cow-hide.jpg', 'asian,modern,scandinavian', 'nayoung@hotmail.com', '4 Asian-Influenced Interiors That Exude the East', 'RM20000'),
(191, 'With many design influences springing from the West â€“ Nordic, Scandinavian, French â€“ we sometimes forget about the luxuries of the East. Simplistic with a taste of a different kind of rustic, they offer modern elegance with a twist. Lush plant life jo', 'portfolio/nayoung_20161205_183121_Simple-Asian-living-room-light-wooden-furniture.jpg', 'asian,modern,scandinavian', 'nayoung@hotmail.com', '4 Asian-Influenced Interiors That Exude the East', 'RM20000'),
(192, 'With many design influences springing from the West â€“ Nordic, Scandinavian, French â€“ we sometimes forget about the luxuries of the East. Simplistic with a taste of a different kind of rustic, they offer modern elegance with a twist. Lush plant life jo', 'portfolio/nayoung_20161205_183121_simplistic-Asian-dining-room-potted-plant-in-concrete.jpg', 'asian,modern,scandinavian', 'nayoung@hotmail.com', '4 Asian-Influenced Interiors That Exude the East', 'RM20000'),
(193, 'With many design influences springing from the West â€“ Nordic, Scandinavian, French â€“ we sometimes forget about the luxuries of the East. Simplistic with a taste of a different kind of rustic, they offer modern elegance with a twist. Lush plant life jo', 'portfolio/nayoung_20161205_183121_simplistic-Asian-dining-room-strokes-of-grey-painting.jpg', 'asian,modern,scandinavian', 'nayoung@hotmail.com', '4 Asian-Influenced Interiors That Exude the East', 'RM20000'),
(194, 'With many design influences springing from the West â€“ Nordic, Scandinavian, French â€“ we sometimes forget about the luxuries of the East. Simplistic with a taste of a different kind of rustic, they offer modern elegance with a twist. Lush plant life jo', 'portfolio/nayoung_20161205_183121_urban-jungle-iron-hanging-lights-brown-leather-couch.jpg', 'asian,modern,scandinavian', 'nayoung@hotmail.com', '4 Asian-Influenced Interiors That Exude the East', 'RM20000'),
(195, 'With many design influences springing from the West â€“ Nordic, Scandinavian, French â€“ we sometimes forget about the luxuries of the East. Simplistic with a taste of a different kind of rustic, they offer modern elegance with a twist. Lush plant life jo', 'portfolio/nayoung_20161205_183121_urban-jungle-living-room-simple-stencil-wooden-table.jpg', 'asian,modern,scandinavian', 'nayoung@hotmail.com', '4 Asian-Influenced Interiors That Exude the East', 'RM20000');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `admin`
--
ALTER TABLE `admin`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `advertisment`
--
ALTER TABLE `advertisment`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `designer`
--
ALTER TABLE `designer`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `portfolio`
--
ALTER TABLE `portfolio`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `admin`
--
ALTER TABLE `admin`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=3;
--
-- AUTO_INCREMENT for table `advertisment`
--
ALTER TABLE `advertisment`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=10;
--
-- AUTO_INCREMENT for table `designer`
--
ALTER TABLE `designer`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=10;
--
-- AUTO_INCREMENT for table `portfolio`
--
ALTER TABLE `portfolio`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=196;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
